spring:

  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mysql:8.0.33:///test
    username: root
    password: test

  sql:
    init:
      mode: always
      schema-locations: classpath*:sql/schema.sql

  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true

  output:
    ansi:
      enabled: always

logging:
  level:
    sql: debug

